version: '3.7'

services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:2.8.4-alpine
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    networks:
      - caddy
    volumes:
      - /tmp/caddy:/var/log/caddy
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    environment:
      - TZ=TIMEZONE_PLACEHOLDER
    deploy:
      labels:
         caddy.email: "TLS_PLACEHOLDER"
         caddy.grace_period: "30s"
      placement:
        constraints:
          - node.role == manager
      replicas: 1
      restart_policy:
        condition: any
      resources:
        reservations:
          cpus: "0.1"
          memory: 100M

networks:
  caddy:
    driver: overlay
    external: true

volumes:
  caddy_data: {}